# Generated by Django 5.0.7 on 2025-11-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_phone_number_alter_person_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_employee',
        ),
        migrations.AlterField(
            model_name='availability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
