# Generated by Django 5.0.7 on 2025-11-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_person_is_customer_remove_person_is_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
    ]
