# Generated by Django 5.0.7 on 2025-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_service_salon'),
        ('users', '0004_remove_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees', to='salon.service'),
        ),
    ]
