# Generated by Django 5.0.7 on 2025-11-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_person_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
    ]
