# Generated by Django 5.0.7 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_employees'),
        ('users', '0006_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='persons', to='salon.service'),
        ),
    ]
