# Generated by Django 5.0.7 on 2025-11-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_role_remove_person_role_remove_person_specialties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
    ]
