# Generated by Django 5.0.7 on 2025-11-30 12:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_person_roles_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('customer', 'Customer'), ('employee', 'Employee')], default='customer', max_length=20),
        ),
    ]
