# Generated by Django 5.0.7 on 2025-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salons/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
