# Generated by Django 5.0.7 on 2025-11-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_salon_image_salon_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
    ]
