# Generated by Django 5.0.7 on 2025-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_service_salon'),
        ('users', '0006_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employee_services', to='users.employee'),
        ),
    ]
