# Generated by Django 5.0.7 on 2025-11-30 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_service_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
