# Generated by Django 5.0.7 on 2025-11-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_service_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_set', to='salon.salon'),
            preserve_default=False,
        ),
    ]
