# Generated by Django 5.0.7 on 2025-11-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal'), ('no_show', 'Gelmedi')], default='pending', max_length=20)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_snapshot', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
