# Generated by Django 5.2.8 on 2025-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
